services:
  web:
    build: .
    ports:
      - "8000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
  redis:
    image: "redis:alpine"
